add_newline = false
scan_timeout = 10

[character]
symbol = "➜"
error_symbol = "✗"
use_symbol_for_status = true
disabled = false

[git]
symbol = " "

[git_branch]
symbol = " "

[git_status]
enabled = true
ahead = ""
behind = ""
diverged = "ﬕ"